### PR TITLE
Add pre-commit config

### PR DESCRIPTION
**Pull request by C-Loftus**
Adds a pre-commit config. Done in a separate PR from #9 so we don't mess up the git blame. 

This is very similar to the config in the template repo. It essentially just applies ruff on every PR so we have a standard format. If we don't like this or want different styles, we can customize ruff with any of its settings listed as it describes here: https://docs.astral.sh/ruff/settings/#extend

### CODE REVIEW

**Comment by C-Loftus** [comment]
Not really clear what is going wrong here. Pre-commit is making all the fixes but it can't push to the branch. I can't see any reason for this myself, but @webb-ben do you know if we have anything in place that would be blocking pre-commit from pushing? (Some sort of security policy/branch protection rule I can't see for any reason?) It says to make sure the branch is up to date, but it is. 

image
image

**Review by webb-ben — APPROVED** [review]
Change prettier to single quotes?

**Comment by C-Loftus** [comment]
Thanks for fixing that. When you get a chance would you mind letting me know how you fixed this? Can't tell from git history

**Comment by webb-ben** [comment]
Fixed the precommit ci?

For some reason precommit can't lint workflow files so I made sure all the files in `.github/workflows/**` and `.pre-commit-config.yml` were properly linted

**Pull request merged**
